blank_issues_enabled: true
contact_links:
  - name: .NET issues
    url: https://github.com/dotnet/runtime#filing-issues
    about: Issues with the runtime, class libraries, frameworks, and SDK should be addressed directly with the .NET team. Documentation on filing issues can be found here.
